name: Build & Smoke Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and start stack
        run: docker compose up -d --build

      - name: Run smoke test
        run: docker compose --profile test up --build --abort-on-container-exit --exit-code-from smoke
